code --install-extension bajdzis.vscode-database
code --install-extension njqdev.vscode-python-typehint
code --install-extension frhtylcn.pythonsnippets
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension github.vscode-pull-request-github
code --install-extension donjayamanne.githistory
code --install-extension ms-azuretools.vscode-docker
code --install-extension cweijan.vscode-database-client2
code --install-extension philsinatra.macos-dark-mode-theme
code --install-extension formulahendry.code-runner
code --install-extension vscode-icons-team.vscode-icons
code --install-extension coenraads.bracket-pair-colorizer-2
code --install-extension naumovs.color-highlight
code --install-extension vscodevim.vim
code --install-extension xadillax.viml
